project_name: asana
version: 2

before:
  hooks:
    - go mod verify
    - go mod tidy

release:
  prerelease: auto
  name_template: "Asana CLI {{ .Version }}"

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/timwehrle/asana/internal/version.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tar.gz
    id: tar
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: asana
    homepage: "https://github.com/timwehrle/asana"
    commit_author:
      name: timwehrle
      email: hello@timwehrle.de
    repository:
      owner: timwehrle
      name: homebrew-asana
      branch: main

changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} by @{{.AuthorUsername}}"
  abbrev: -1
  sort: asc
  filters:
    exclude:
      - "^tests:"
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 2
    - title: "Build process updates"
      regexp: '^.*?(build|ci)(\(.+\))??!?:.+$S'
      order: 3
    - title: "Dependency updates"
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 4
    - title: "Documentation updates"
      regexp: '^.*?docs?(\(.+\))??!?:.+$'
      order: 5
    - title: "Other updates"
      order: 999


checksum:
  name_template: "checksums.txt"