name: Go Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Running Linter
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout=5m

      - name: Check Formatting
        run: test -z "$(gofmt -s -l -e .)"

      - name: Running Tests
        run: make test